version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "54881:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: