// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	ToDoApp "ToDoApp"

	mock "github.com/stretchr/testify/mock"
)

// TodoList is an autogenerated mock type for the TodoList type
type TodoList struct {
	mock.Mock
}

// Create provides a mock function with given fields: userId, list
func (_m *TodoList) Create(userId int, list ToDoApp.TodoList) (int, error) {
	ret := _m.Called(userId, list)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int, ToDoApp.TodoList) (int, error)); ok {
		return rf(userId, list)
	}
	if rf, ok := ret.Get(0).(func(int, ToDoApp.TodoList) int); ok {
		r0 = rf(userId, list)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, ToDoApp.TodoList) error); ok {
		r1 = rf(userId, list)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: userId, listId
func (_m *TodoList) Delete(userId int, listId int) error {
	ret := _m.Called(userId, listId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(userId, listId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: userId
func (_m *TodoList) GetAll(userId int) ([]ToDoApp.TodoList, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []ToDoApp.TodoList
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]ToDoApp.TodoList, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int) []ToDoApp.TodoList); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ToDoApp.TodoList)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: userId, listId
func (_m *TodoList) GetById(userId int, listId int) (ToDoApp.TodoList, error) {
	ret := _m.Called(userId, listId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 ToDoApp.TodoList
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (ToDoApp.TodoList, error)); ok {
		return rf(userId, listId)
	}
	if rf, ok := ret.Get(0).(func(int, int) ToDoApp.TodoList); ok {
		r0 = rf(userId, listId)
	} else {
		r0 = ret.Get(0).(ToDoApp.TodoList)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(userId, listId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: userId, listId, input
func (_m *TodoList) Update(userId int, listId int, input ToDoApp.UpdateListInput) error {
	ret := _m.Called(userId, listId, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, ToDoApp.UpdateListInput) error); ok {
		r0 = rf(userId, listId, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTodoList creates a new instance of TodoList. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoList(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoList {
	mock := &TodoList{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
